import { Card } from "@nextui-org/react";
import Head from "next/head";
import React from "react";

export default function Help() {
	return (
		<div>
			<Head>
				<title>Help</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8">
				<Card
					style={{
						display: "flex",
						alignItems: "center",
						minHeight: "200px",
						marginTop: "15px",
						padding: "5px",
					}}
				>
					<h1 style={{ fontSize: "2.5rem", marginTop: "15px" }}>Help</h1>
					<p style={{ marginBottom: "15px" }}>ติดต่อ แจ้ง ปัญหา</p>
				</Card>
			</div>
		</div>
	);
}
