import { Card, Container, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import React from "react";

// Contents
import GroupImg from "../assets/index-content/group.jpg";

export default function index() {
	return (
		<div>
			<Head>
				<title>CMRU SCI 66</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container maxWidth="mb" sx={{ pt: 15, pb: 5 }}>
				<Card>
					<Container sx={{ pt: 3 }}>
						<Typography component="h1" variant="h4" textAlign="center">
							Welcome To Computer Science 66
						</Typography>
						<Typography component="h4" variant="h6" textAlign="center">
							เว็บไซต์นี้สร้างขึ้นมาเพื่อเป็นแหล่งศูนย์รวมของนักศึกษา
							คณะวิทยาศาสตร์และเทคโนโลยี สาขา วิทยาการคอมพิวเตอร์ ทั้ง 2
							หมู่เรียน วค66.วท.บ.4.1 และ วค66.วท.บ.4.2
						</Typography>
						<Image
							src={GroupImg}
							width={1200}
							height={650}
							className="responsive-img"
							alt="Group"
							priority
						/>
					</Container>
				</Card>
			</Container>
		</div>
	);
}
