import { Card, Container, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";

export default function login() {
	return (
		<div>
			<Head>
				<title>Login Page</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container sx={{ pt: 15, pb: 5 }}>
				<Card>
					<Container maxWidth="sm" sx={{ pt: 5, pb: 3 }}>
						<Typography component="h1" variant="h4" textAlign="center">
							Login
						</Typography>
					</Container>
				</Card>
			</Container>
		</div>
	);
}
