import React from "react";
import Head from "next/head";
import { Card, Container, TextField, Typography, Button } from "@mui/material";
import { AdapterDayjs } from "@mui/x-date-pickers/AdapterDayjs";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { DatePicker } from "@mui/x-date-pickers/DatePicker";

export default function Uploadsub() {
	return (
		<div>
			<Head>
				<title>Upload</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container maxWidth="sm" sx={{ pt: 15, pb: 5 }}>
				<Card className="upload-form">
					<Container sx={{ pt: 5, pb: 3 }}>
						<Typography component="h1" variant="h4" textAlign="center">
							Upload Subject Info
						</Typography>
						<Typography component="h1" variant="h5" textAlign="center">
							ยินดีต้อนหรับผู้รับผิดชอบในการ
							อัพโหลดข้อมูลงานที่ได้รับมอบหมายให้เพื่อนใน Section 1 Section 2
						</Typography>
						<Typography component="h1" variant="h5" textAlign="center">
							กรอกข้อมูล รายวิชา
						</Typography>
						<Typography component="h1" variant="h6" textAlign="left">
							หัวเรื่อง
						</Typography>
						<TextField
							type="text"
							margin="normal"
							required
							fullWidth
							id="title"
							label="หัวเรื่อง"
							autoComplete="title"
							autoFocus
						/>
						<Typography component="h1" variant="h6" textAlign="left">
							งานที่ 1
						</Typography>
						<TextField
							type="text"
							margin="normal"
							required
							fullWidth
							id="content1"
							label="งานที่ 1"
							autoComplete="content1"
							autoFocus
						/>
						<Typography component="h1" variant="h6" textAlign="left">
							งานที่ 2
						</Typography>
						<TextField
							type="text"
							margin="normal"
							fullWidth
							id="content2"
							label="งานที่ 2"
							autoComplete="content2"
							autoFocus
						/>
						<Typography component="h1" variant="h6" textAlign="left">
							งานที่ 3
						</Typography>
						<TextField
							type="text"
							margin="normal"
							fullWidth
							id="content3"
							label="งานที่ 3"
							autoComplete="content 3"
							autoFocus
						/>
						<Typography component="h1" variant="h6" textAlign="left">
							วันที่สั่ง
						</Typography>
						<LocalizationProvider dateAdapter={AdapterDayjs}>
							<DatePicker />
						</LocalizationProvider>
						<Typography component="h1" variant="h6" textAlign="left">
							กำหนดส่งงานวันที่
						</Typography>
						<LocalizationProvider dateAdapter={AdapterDayjs}>
							<DatePicker />
						</LocalizationProvider>
						<Button
							type="submit"
							fullWidth
							variant="contained"
							sx={{ mt: 3, mb: 2 }}
						>
							อัพโหลดข้อมูล
						</Button>
					</Container>
				</Card>
			</Container>
		</div>
	);
}
