import { faFacebookF, faGithub } from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { Card, Image } from "@nextui-org/react";
import Head from "next/head";
import Link from "next/link";

export default function about() {
	const leadersData = [
		{
			name: "John Doe",
			role: "Software Engineer",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
			facebookLink: "https://www.facebook.com/johndoe",
			githubLink: "https://github.com/johndoe",
		},
		{
			name: "Jane Smith",
			role: "Product Manager",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
		{
			name: "John Doe",
			role: "Software Engineer",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
			facebookLink: "https://www.facebook.com/johndoe",
			githubLink: "https://github.com/johndoe",
		},
		{
			name: "Jane Smith",
			role: "Product Manager",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
		{
			name: "John Doe",
			role: "Software Engineer",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
			facebookLink: "https://www.facebook.com/johndoe",
			githubLink: "https://github.com/johndoe",
		},
		{
			name: "Jane Smith",
			role: "Product Manager",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
		{
			name: "John Doe",
			role: "Software Engineer",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
			facebookLink: "https://www.facebook.com/johndoe",
			githubLink: "https://github.com/johndoe",
		},
	];

	const SecterleadersData = [
		{
			name: "John Doe",
			role: "Software Engineer",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
			facebookLink: "https://www.facebook.com/johndoe",
			githubLink: "https://github.com/johndoe",
		},
		{
			name: "Jane Smith",
			role: "Product Manager",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
	];

	const DeveloperData = [
		{
			name: "Faelayis",
			role: "Fullstack Devpeloper",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258a2462d826712d",
			facebookLink: "https://www.facebook.com/johndoe",
			githubLink: "https://github.com/Faelayis",
		},
		{
			name: "Zismil",
			role: "Fullstack Devpeloper",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258114e29026708c",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/zismaildev",
		},
		{
			name: "Nin",
			role: "UX|UI Webdesing",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
		{
			name: "Guy",
			role: "Contents",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258114e29026302d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
		{
			name: "Njitym29",
			role: "Image and Logo",
			sharp: '"Never give up"',
			avatar: "https://i.pravatar.cc/150?u=a04258114e29026302d",
			facebookLink: "https://www.facebook.com/janesmith",
			githubLink: "https://github.com/janesmith",
		},
	];
	return (
		<div>
			<Head>
				<title>About</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8">
				<Card
					style={{
						display: "flex",
						flexDirection: "column",
						alignItems: "center",
						justifyContent: "center",
						minHeight: "200px",
						marginTop: "15px",
						padding: "5px",
					}}
				>
					<h1 style={{ fontSize: "2.5rem", marginTop: "15px" }}>About Us</h1>
					<div className="px-8 py-6">
						<p style={{ marginBottom: "15px", textIndent: "2em" }}>
							เว็บไซต์นี้สร้างขึ้นมาโดย Next.js Framework และใช้ NextUI
							ในการตกแต่งและสร้าง Component ต่างๆในการตกแต่งและออกแบบ Interface
							ของหน้า WebPage สร้างขึ้นโดยนักศึกษา คณะวิทยาศาสตร์และเทคโนโลยี
							สาขาวิทยาการคอมพิวเตอร์
						</p>
					</div>
					{/*  Leaders */}
					<div className="px-8 py-6">
						<h1 className="mb-4 text-2xl font-bold">7 Leader</h1>
						<p className="mb-8 text-gray-500">7 ผู้นำ วิทยาการคอมพิวเตอร์ 66</p>
						<div className="grid grid-cols-3 gap-8">
							{leadersData.map((leader, index) => (
								<div
									key={index}
									className="flex space-x-4 rounded-md bg-gray-100 p-4"
								>
									<Image
										src={leader.avatar}
										alt={leader.name}
										className="h-16 w-16 rounded-full"
									/>
									<div className="grow">
										<h3 className="text-lg font-semibold">{leader.name}</h3>
										<p className="text-gray-500">{leader.role}</p>
										<p className="text-gray-500">{leader.sharp}</p>
									</div>
									<div className="flex items-center space-x-2">
										<Link
											target="_blank"
											href={leader.facebookLink}
											className="text-black hover:text-red-500"
										>
											<FontAwesomeIcon icon={faFacebookF} className="h-4 w-4" />
										</Link>
										<Link
											target="_blank"
											href={leader.githubLink}
											className="text-black hover:text-red-500"
										>
											<FontAwesomeIcon icon={faGithub} className="h-4 w-4" />
										</Link>
									</div>
								</div>
							))}
						</div>
						{/*  Secterleaders */}
						<div className="mt-7">
							<h1 className="mb-4 text-2xl font-bold">Section Leader</h1>
							<p className="mb-8 text-gray-500">หัวหน้าหมู่เรียน</p>
							<div className="grid grid-cols-3 gap-8">
								{SecterleadersData.map((leader, index) => (
									<div
										key={index}
										className="flex space-x-4 rounded-md bg-gray-100 p-4"
									>
										<Image
											src={leader.avatar}
											alt={leader.name}
											className="h-16 w-16 rounded-full"
										/>
										<div className="grow">
											<h3 className="text-lg font-semibold">{leader.name}</h3>
											<p className="text-gray-500">{leader.role}</p>
											<p className="text-gray-500">{leader.sharp}</p>
										</div>
										<div className="flex items-center space-x-2">
											<Link
												target="_blank"
												href={leader.facebookLink}
												className="text-black hover:text-red-500"
											>
												<FontAwesomeIcon
													icon={faFacebookF}
													className="h-4 w-4"
												/>
											</Link>
											<Link
												target="_blank"
												href={leader.githubLink}
												className="text-black hover:text-red-500"
											>
												<FontAwesomeIcon icon={faGithub} className="h-4 w-4" />
											</Link>
										</div>
									</div>
								))}
							</div>
						</div>
						{/* Developers */}
						<div className="mt-7">
							<h1 className="mb-4 text-2xl font-bold">Developers</h1>
							<p className="mb-8 text-gray-500">
								7 ผู้นำ วิทยาการคอมพิวเตอร์ 66
							</p>
							<div className="grid grid-cols-3 gap-8">
								{DeveloperData.map((developer, index) => (
									<div
										key={index}
										className="flex space-x-4 rounded-md bg-gray-100 p-4"
									>
										<Image
											src={developer.avatar}
											alt={developer.name}
											className="h-16 w-16 rounded-full"
										/>
										<div className="grow">
											<h3 className="text-lg font-semibold">
												{developer.name}
											</h3>
											<p className="text-gray-500">{developer.role}</p>
											<p className="text-gray-500">{developer.sharp}</p>
										</div>
										<div className="flex items-center space-x-2">
											<Link
												target="_blank"
												href={developer.facebookLink}
												className="text-black hover:text-red-500"
											>
												<FontAwesomeIcon
													icon={faFacebookF}
													className="h-4 w-4"
												/>
											</Link>
											<Link
												target="_blank"
												href={developer.githubLink}
												className="text-black hover:text-red-500"
											>
												<FontAwesomeIcon icon={faGithub} className="h-4 w-4" />
											</Link>
										</div>
									</div>
								))}
							</div>
						</div>

						{/* Test */}
						<div className="mt-7">
							<h1 className="mb-4 text-2xl font-bold">Test</h1>
							<p className="mb-8 text-gray-500">
								7 ผู้นำ วิทยาการคอมพิวเตอร์ 66
							</p>
							{/* <div className="grid grid-cols-3 gap-8">
								{DeveloperData.map((developer, index) => (
									<Card>
										<div></div>
									</Card>
								))}
							</div> */}
						</div>
					</div>
				</Card>
			</div>
		</div>
	);
}
