import { UploadOutlined } from "@ant-design/icons";
import { DiscordWebHook } from "@cmru-comsci-66/api";
import {
	Autocomplete,
	Box,
	Card,
	CardContent,
	Container,
	Grid,
	TextField,
	Typography,
} from "@mui/material";
import CircularProgress from "@mui/material/CircularProgress";
import { Button, Upload } from "antd";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import Swal from "sweetalert2";

import BillingImg from "@/assets/bill/bill.jpg";

import { useBillings } from "../api/billings";
import { useStudent } from "../api/student";

export default function Finance() {
	const {
		billings,
		isLoading: billingsIsLoading,
		isError: billingsIsError,
	} = useBillings();
	const {
		student,
		isLoading: studentIsLoading,
		isError: studentIsError,
	} = useStudent();
	const [fullname, setFullname] = useState("");
	const [studentid, setStudentId] = useState("");
	const [price, setPrice] = useState("");
	const [pricePlace, setPricePlace] = useState("0");
	const [note, setNote] = useState("");
	const [selectedFile, setSelectedFile] = useState(null);
	const [dropdown, setDropDown] = useState("");
	const [isCooldown, setIsCooldown] = useState(false);

	const swrIsError = billingsIsError || studentIsError;

	if (swrIsError) {
		Swal.fire({
			icon: "error",
			title: `พบข้อผิดพลาด`,
			footer: `${
				swrIsError.code ?? swrIsError.status
					? `${swrIsError.code ?? swrIsError.status}:`
					: ""
			} ${swrIsError.message} `,
		});

		return <div></div>;
	}

	if (billingsIsLoading || studentIsLoading)
		return (
			<Container fullWidth sx={{ pt: 15, pb: 5 }}>
				<Box
					display="flex"
					justifyContent="center"
					alignItems="center"
					sx={{ display: "flex" }}
				>
					<CircularProgress color="info" thickness={4.5} size={100} />
				</Box>
			</Container>
		);

	const handleSubmit = async (event) => {
		event.preventDefault();

		if (!studentid || !price || !dropdown || !selectedFile) {
			Swal.fire({
				icon: "warning",
				title: "ข้อมูลไม่ครบถ้วน",
				text: "กรุณากรอกข้อมูลให้ครบถ้วนก่อนที่จะส่งข้อมูล",
			});
			return;
		}

		if (!selectedFile.type.startsWith("image/")) {
			Swal.fire({
				icon: "warning",
				title: "ข้อมูลไม่ถูกต้อง",
				text: "กรุณาส่งไฟล์สลิปประเภทรูปภาพ",
			});
			return;
		}

		if (isCooldown) {
			Swal.fire({
				icon: "warning",
				title: "Cooldown",
				text: "ใจเย็นสิ๊ อย่า สแปมสิ",
			});
			return;
		}

		setIsCooldown(process.env.NODE_ENV !== "development");

		const webhook = new DiscordWebHook(
			dropdown?.id ?? process.env.DISCORD_WEBHOOK_ID,
			dropdown?.token ?? process.env.DISCORD_WEBHOOK_TOKEN,
		);

		try {
			await webhook
				.Send(selectedFile, { fullname, price, studentid, note })
				.then((data) => {
					if (data?.status === 204 || (data?.webhook_id && data?.channel_id)) {
						Swal.fire({
							icon: "success",
							title: "เสร็จสิ้น",
							text: "ข้อมูลถูกส่งเรียบร้อยแล้ว",
						});
					} else {
						Swal.fire({
							icon: "error",
							title: `พบข้อผิดพลาด`,
							text: "WebHook เน่าส่งใหม่ภายหลังนะจ๊ะ",
							footer: `${data.code !== 0 ? `${data.code}: ` : ""}${
								data.message
							} `,
						});
					}
				});
		} catch (error) {
			Swal.fire({
				icon: "error",
				title: `พบข้อผิดพลาด`,
				text: error.notify ? error.notify : null,
				footer: `${error.code}: ${error.message} `,
			});
		}

		if (process.env.NODE_ENV !== "development") {
			setTimeout(() => {
				setIsCooldown(false);
			}, 5000);
		}
	};

	return (
		<div>
			<Head>
				<title>Finance</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container fullWidth sx={{ pt: 15, pb: 5 }}>
				<Card>
					<Container sx={{ pt: 3 }} className="finance">
						<Typography
							component="h1"
							variant="h4"
							textAlign="center"
							style={{ color: "white" }}
						>
							Finance
						</Typography>
						<Grid container spacing={3}>
							<Grid item md={4} xs={12}>
								<Card
									sx={{
										height: "100%",
										display: "flex",
										flexDirection: "column",
										cursor: "pointer",
									}}
								>
									<Image
										src={BillingImg}
										width={1000}
										height={1000}
										style={{ width: "auto", height: "auto" }}
										alt="Profile"
										className="responsive-img"
										priority
									/>
								</Card>
							</Grid>
							<Grid item md={4} xs={12}>
								<Card
									sx={{
										height: "100%",
										display: "flex",
										flexDirection: "column",
										cursor: "pointer",
									}}
								>
									<CardContent sx={{ flexGrow: 1 }}>
										<Box
											component="form"
											sx={{ mt: 1 }}
											onSubmit={handleSubmit}
										>
											<Typography
												component="h1"
												variant="h4"
												textAlign="center"
											>
												ข้อมูลการชำระเงิน
											</Typography>
											<Autocomplete
												margin="normal"
												fullWidth
												id="fullname"
												label="ขื่อ-สกุล"
												autoFocus
												Autocomplete={true}
												options={student
													.map((item) => {
														return {
															label: item.name,
															section: item.section,
														};
													})
													.sort()}
												value={fullname}
												renderInput={(params) => (
													<TextField {...params} label="ขื่อ-สกุล" />
												)}
												onChange={(e, value) => {
													const checkStudent = student?.filter((d) =>
														d.name.match(value?.label),
													)[0];

													setFullname(value?.label ?? "");
													if (checkStudent && value) {
														setStudentId(checkStudent.id.toString());
													} else {
														setStudentId("");
													}
												}}
											/>
											<TextField
												type="number"
												margin="normal"
												required
												fullWidth
												inputProps={{ maxLength: 8 }}
												id="studentid"
												label="รหัสนักศึกษา"
												autoComplete="studentid"
												autoFocus
												value={studentid}
												placeholder="66143XXX หรือ XXX"
												defaultValue={studentid}
												onChange={(e) => {
													const value = e.target.value;
													const checkStudent = student?.filter(
														(d) =>
															d.id.toString() ===
															(value.length <= 3 ? `66143${value}` : value),
													)[0];

													setStudentId(value.slice(0, 8));
													if (checkStudent && value) {
														setFullname(checkStudent.name.toString());
													} else {
														setFullname("");
													}
												}}
											/>
											<TextField
												type="text"
												margin="normal"
												required
												fullWidth
												id="price"
												label="จำนวนเงิน"
												autoComplete="price"
												autoFocus
												value={price}
												placeholder={pricePlace}
												onChange={(e) => setPrice(e.target.value)}
											/>
											<TextField
												type="text"
												margin="normal"
												fullWidth
												id="note"
												label="หมายเหตุ"
												autoComplete="note"
												autoFocus
												value={note}
												onChange={(e) => setNote(e.target.value)}
											/>
											<Autocomplete
												margin="normal"
												required
												fullWidth
												disablePortal
												id="dropdown"
												value={dropdown}
												options={billings}
												sx={{ mt: 2 }}
												renderInput={(params) => (
													<TextField {...params} label="กิจกรรม" />
												)}
												onChange={(e, v) => {
													v?.price
														? (setPrice(v.price), setPricePlace(v.price))
														: (setPrice(""), setPricePlace("0"));
													setDropDown(v);
												}}
											/>
										</Box>
									</CardContent>
								</Card>
							</Grid>
							<Grid item md={4} xs={12} sx={{ pb: 5 }}>
								<Card
									sx={{
										height: "100%",
										display: "flex",
										flexDirection: "column",
										cursor: "pointer",
									}}
								>
									<CardContent sx={{ flexGrow: 1 }}>
										<Box
											component="form"
											sx={{ mt: 1 }}
											onSubmit={handleSubmit}
										>
											<Typography
												component="h1"
												variant="h4"
												textAlign="center"
											>
												อัพโหลดข้อมูล
											</Typography>
											<Upload
												listType="picture"
												beforeUpload={(file) => {
													setSelectedFile(file);
													return false;
												}}
											>
												<Button
													variant="contained"
													color="primary"
													icon={<UploadOutlined />}
												>
													เพิ่มสลิป
												</Button>
											</Upload>
											<Box
												sx={{
													display: "flex",
													justifyContent: "center",
													marginTop: "1rem",
												}}
											>
												<Button
													type="primary"
													block
													variant="contained"
													htmlType="submit"
												>
													ส่ง
												</Button>
											</Box>
										</Box>
									</CardContent>
								</Card>
							</Grid>
						</Grid>
					</Container>
				</Card>
			</Container>
		</div>
	);
}
