import { Card } from "@nextui-org/react";
import Head from "next/head";

export default function Gallery() {
	return (
		<div>
			<Head>
				<title>Gallery</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8">
				<Card>
					<div className="px-8 py-6">
						<h2 className="mt-3 p-5 text-center text-3xl font-bold tracking-tight sm:text-4xl">
							Gallery
						</h2>
					</div>
				</Card>
			</div>
		</div>
	);
}
