import { Card, Container, Typography } from "@mui/material";
import Image from "next/image";
import Head from "next/head";
import React from "react";

// Contents

export default function History() {
	return (
		<div>
			<Head>
				<title>History</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container maxWidth="mb" sx={{ pt: 15, pb: 5 }}>
				<Card>
					<Container sx={{ pt: 3 }}>
						<Typography component="h1" variant="h4" textAlign="center">
							History
						</Typography>
						<Typography component="h4" variant="h6" textAlign="center">
							ประวัติการจ่ายเงินของกิจกรรมต่างๆ ของรุ่น
						</Typography>

						<Typography
							sx={{ pt: 25, pb: 25 }}
							component="h1"
							variant="h4"
							textAlign="center"
							style={{ color: "red" }}
						>
							Coming Soon
						</Typography>
					</Container>
				</Card>
			</Container>
		</div>
	);
}
