import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Card, CardContent, Container, Typography, Grid } from "@mui/material";

const pages = [
	"Multimedia",
	"Math",
	"Desigeprogram",
	"Digitalliteracy",
	"Holisticcare",
	"Thai",
];

export default function Section1() {
	const handleToPage = (page) => {
		window.location.href = `/contents/subject/${page.toLowerCase()}`;
	};

	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container maxWidth="mb" sx={{ pt: 15, pb: 5 }}>
				<Card className="Card-Bg">
					<Typography
						component="h1"
						variant="h4"
						textAlign="center"
						mt={7}
						sx={{
							"& .text-black": {
								color: "black",
							},
							"& .text-red": {
								color: "red",
							},
						}}
					>
						<span className="text-black">งาน </span>
						<span className="text-red">ที่ได้รับมอบหมาย </span>
					</Typography>
					<Typography component="h1" variant="h5" textAlign="center">
						เว็บไซต์นี้สร้างขึ้นเพื่อติดตามงานที่ได้รับมอบหมายของ Section 1
					</Typography>

					<Typography
						sx={{ pt: 25, pb: 25 }}
						component="h1"
						variant="h4"
						textAlign="center"
					>
						No Data
					</Typography>
				</Card>
			</Container>
		</div>
	);
}
