import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Card, CardContent, Container, Typography, Grid } from "@mui/material";

const pages = [
	"Multimedia",
	"Math",
	"Desigeprogram",
	"Digitalliteracy",
	"Holisticcare",
	"Thai",
];
import { api } from "../api/subject";

export async function getServerSideProps() {
	return api();
}

export default function Section2({ subject }) {
	const handleToPage = (page) => {
		window.location.href = `/subjects/${page.toLowerCase()}`;
	};

	return (
		<div>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Container maxWidth="mb" sx={{ pt: 15, pb: 5 }}>
				<Card className="Card-Bg">
					<Typography
						component="h1"
						variant="h4"
						textAlign="center"
						mt={7}
						sx={{
							"& .text-black": {
								color: "black",
							},
							"& .text-red": {
								color: "red",
							},
						}}
					>
						<span className="text-black">งาน </span>
						<span className="text-red">ที่ได้รับมอบหมาย </span>
					</Typography>
					<Typography component="h1" variant="h5" textAlign="center">
						เว็บไซต์นี้สร้างขึ้นเพื่อติดตามงานที่ได้รับมอบหมายของ Section 2
					</Typography>
					<Grid container spacing={4} p={5}>
						{subject.map(
							(
								item,
								index, // เพิ่มตัวแปร index ที่นี่
							) => (
								<Grid item key={item.id} md={4}>
									<Card
										sx={{
											height: "100%",
											display: "flex",
											flexDirection: "column",
											cursor: "pointer",
										}}
										className="responsive-img"
										onClick={() => handleToPage(pages[index])} // ใช้ index แทน item.id
									>
										<Image
											src={item.src}
											width={320}
											height={220}
											style={{ width: "auto", height: "auto" }}
											alt="random"
											priority
											layout="responsive"
											objectFit="cover"
											objectPosition="center"
											sizes="(max-width: 320px) 280px, (max-width: 640px) 600px, 400px"
										/>
										<CardContent sx={{ flexGrow: 1 }}>
											<Typography gutterBottom variant="h5" component="h2">
												{item.title}
											</Typography>
											<Typography className="text-indent">
												รหัสวิชา: {item.coursecode}
											</Typography>
											<Typography className="text-indent">
												อาจารย์ผู้สอน: {item.instructorName}
											</Typography>
										</CardContent>
									</Card>
								</Grid>
							),
						)}
					</Grid>
				</Card>
			</Container>
		</div>
	);
}
