import { Card } from "@nextui-org/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";

export default function todo() {
	return (
		<div>
			<Head>
				<title>ToDo</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto max-w-7xl py-24 sm:px-6 sm:py-32 lg:px-8">
				<Card className="mt-15px flex min-h-[200px] flex-col items-center p-5">
					<h1 className="text-2.5xl mt-15px">ToDo Page</h1>
					<p className="mb-15px text-indent-[2em]">
						งานที่ได้รับมอบหมายของทั้ง 2 Section
					</p>
					<div className="mt-8 flex space-x-4">
						<Link href="/contents/section1">
							<img
								src="/image1.jpg" // URL ของรูปภาพ
								alt="Section 1"
								className="h-auto max-w-full"
							/>
						</Link>
						<Link href="/contents/section2">
							<img
								src="/image2.jpg" // URL ของรูปภาพ
								alt="Section 2"
								className="h-auto max-w-full"
							/>
						</Link>
					</div>
				</Card>
			</div>
		</div>
	);
}
