import React from "react";
import { Card, CardContent, Container, Grid, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";

// Contents
import Section1Img from "@/assets/section/section1.png";
import Section2Img from "@/assets/section/section2.png";

export default function ToDo() {
	const handleSection1Click = () => {
		window.location.href = "/contents/section1"; // เปลี่ยน URL เป็นที่ต้องการสำหรับหน้า section1
	};

	const handleSection2Click = () => {
		window.location.href = "/contents/section2"; // เปลี่ยน URL เป็นที่ต้องการสำหรับหน้า section2
	};

	return (
		<div>
			<Head>
				<title>To-Do</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container maxWidth="mb" sx={{ pt: 15, pb: 5 }}>
				<Card>
					<Container sx={{ pt: 3 }}>
						<Typography component="h1" variant="h4" textAlign="center">
							Welcome To Todo Page
						</Typography>

						<Grid container spacing={3} p={5}>
							<Grid item md={6} sm={12}>
								<Card
									sx={{
										height: "100%",
										display: "flex",
										flexDirection: "column",
										cursor: "pointer",
									}}
									onClick={handleSection1Click}
									className="hover-zoom"
								>
									<Image
										src={Section1Img}
										width={450}
										height={350}
										alt="Profile"
										className="responsive-img"
										priority
									/>
								</Card>
							</Grid>

							<Grid item md={6} sm={12}>
								<Card
									sx={{
										height: "100%",
										display: "flex",
										flexDirection: "column",
										cursor: "pointer",
									}}
									onClick={handleSection2Click}
									className="hover-zoom"
								>
									<Image
										src={Section2Img}
										width={450}
										height={250}
										alt="Profile"
										className="responsive-img"
										priority
									/>
								</Card>
							</Grid>
						</Grid>
					</Container>
				</Card>
			</Container>
		</div>
	);
}
