// pages/dashboard.js
import { Card } from "@nextui-org/react";
import Head from "next/head";
import { useSession } from "next-auth/react";

export default function Dashboard() {
	const { data: session } = useSession();

	// ตรวจสอบว่า session มีค่าและมีบทบาทเป็น "developer" หรือไม่
	const isDeveloper = session?.user?.role === "developer";

	return (
		<div>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="mx-auto max-w-7xl p-5 py-24 sm:px-6 sm:py-32 lg:px-8">
				{isDeveloper ? (
					<Card
						style={{
							display: "flex",
							alignItems: "center",
							minHeight: "200px",
							marginTop: "15px",
							padding: "5px",
						}}
					>
						<h1 style={{ fontSize: "2.5rem", marginTop: "15px" }}>Dashboard</h1>
					</Card>
				) : (
					<p>คุณไม่มีสิทธิ์เข้าถึงหน้านี้</p>
				)}
			</div>
		</div>
	);
}
