// pages/dashboard.js
import { Card } from "@nextui-org/react";
import Head from "next/head";
import { useSession } from "next-auth/react";

import UsageComp from "@/components/admin/usage";

export default function Dashboard() {
	const { data: session } = useSession();

	const isDeveloper = session?.user?.role === "developer";

	return (
		<div>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="max-w-8xl mx-auto p-5 py-24 sm:px-6 sm:py-32 lg:px-8">
				{isDeveloper ? (
					<Card
						style={{
							display: "flex",
							alignItems: "center",
							minHeight: "200px",
							marginTop: "15px",
							padding: "5px",
						}}
					>
						<h1
							style={{
								fontSize: "2.5rem",
								marginTop: "15px",
								marginBottom: "15px",
							}}
						>
							Dashboard
						</h1>
						<UsageComp />
					</Card>
				) : (
					<div className="text-center">
						<h2 className="mt-3 p-5 text-center text-3xl font-bold tracking-tight sm:text-4xl">
							คุณไม่มีสิทธ์เข้าถึงหน้านี้
						</h2>
					</div>
				)}
			</div>
		</div>
	);
}
